name: CRM Flask CI/CD

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Kodni yuklash
      uses: actions/checkout@v3

    - name: Python o‘rnatish
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Kutubxonalarni o‘rnatish
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Testdan o‘tkazish
      run: echo "✅ Testlar joyida"

    - name: Deploy qilish (agar SSH orqali)
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          cd /root/Networking-in-the-cloud
          git pull origin main
          docker build -t crm-flask .
          docker stop crm || true
          docker rm crm || true
          docker run -d --name crm -p 5000:5000 crm-flask
